
export const UNSPLASH_PHOTO_REQUEST = 'UNSPLASH_PHOTO_REQUEST';
export const UNSPLASH_PHOTO_REQUEST_SUCCESS = 'UNSPLASH_PHOTO_REQUEST_SUCCESS';
export const UNSPLASH_PHOTO_REQUEST_FAILURE = 'UNSPLASH_PHOTO_REQUEST_FAILURE';